### PR TITLE
Snakemake

### PR DESCRIPTION
**Pull request by jmtsuji**
Improvements to user experience, including:

- Optionally specify a directory to store conda envs for future use
- Flexible subject genome extensions
- Append custom snakemake args to a command
- Removal of additional temp files
- Simplification of output file/folder structure

In addition, test input/output data is now provided (usable for future end-to-end testing)

### CODE REVIEW

**Comment by jmtsuji** [comment]
@LeeBergstrand Mind checking over this before I merge? Thanks.

**Comment by jmtsuji** [comment]
@LeeBergstrand The key files to review are:
- `BackBLAST.sh`
- `Snakefile`
- `template_config.yaml`

I added new features to the workflow, which is reflected in these three files.

Otherwise, I made minor edits to:
- `BackBLAST.py` -- I realized that it is fine to keep the e-value as a string because it is passed to the command line as a string argument anyway. Single change to the code.
- `README.md` -- I added a few preliminary comments on how to install/use the pipeline, to be expanded upon later.

Test data is also added.

**Comment by LeeBergstrand** [comment]
@jmtsuji Before I review this can you split BackBLAST.sh into a couple of separate files? It feels a bit long. A few of those functions you might be able to put in a separate script.

**Comment by LeeBergstrand** [comment]
> @jmtsuji Before I review this can you split BackBLAST.sh into a couple of separate files? It feels a bit long. A few of those functions you might be able to put in a separate script.

As in sub bash scripts that carryout specific functionality.

**Comment by LeeBergstrand** [comment]
@jmtsuji Can you remove the amount of test genomes? How many are their now? We should use the absolute bear minimum. Also for the test data we should strip the genomes down to maybe 20 gene up and down from genome cluster, rather han the whole genome. At this rate every one of those example genomes is going to be like 2 mb each. That means the CI system will have to down load like 10MB of data every time it runs. This is also going to force us to have the CI system run a long time to test blast on all those files. At my company we use something very small like a lambda phage genome.

**Comment by LeeBergstrand** [comment]
@jmtsuji Gitignore the log files

**Comment by jmtsuji** [comment]
@LeeBergstrand Thanks for the initial comments.

Splitting `BackBLAST.sh` -- done. Functions for generating template files are now in a separate Bash script that can be run independently or sourced. I've put this in the `scripts` folder. Once this branch is merged, I hope to do a major restructuring of what files are stored in what folders in the repo (e.g., move everything in the `Visualization` folder into the `scripts` folder).

Log files -- now removed and subject to `.gitignore`

Test genomes -- there were 7 test genomes plus 1 query genome = 8 genomes. ~7-8 MB total size. I've now reduced the test dataset size to ~100 KB by only taking ~5 genes up/downstream of each BLAST target.

Very good to know that we cannot delete the test files I already committed without some extra effort. Sorry about this... :-/ Longer-term, we will probably have to clean the repo anyway, however. The original version of BackBLAST contained a couple hundred MB of example data.

**Comment by LeeBergstrand** [comment]
@jmtsuji Ready to merge see comment above. Congrats!

**Comment by jmtsuji** [comment]
@LeeBergstrand Thanks once again for all your feedback. Great learning opportunity.

**Pull request merged**
